# A lot of this was taken from https://github.com/philsquared/Catch
language: cpp
sudo: false

os:
  - linux
  - osx
compiler: 
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
matrix:
  allow_failures:
    - os: osx

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz
      tar -xzf cmake-3.4.3-Linux-x86_64.tar.gz      
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Darwin-x86_64.tar.gz
      tar -xzf cmake-3.4.3-Darwin-x86_64.tar.gz
    fi

before_script:
  - export CXX=${COMPILER}
  - export CMAKE_DIR=$(pwd)
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      export CMAKE_DIR=$(pwd)/cmake-3.4.3-Linux-x86_64/bin
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      export CMAKE_DIR=$(pwd)/cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/bin
    fi

  - cd ${TRAVIS_BUILD_DIR}
  - cmake --version
  - ${CMAKE_DIR}/cmake --version
  - ${CMAKE_DIR}/cmake . -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cd build

script:
  - make -j 2
  - ctest -V -j 2

notifications:
  email: false
  slack:
    secure: eWomj3OJ9UtPP4/jGYQ2o+vbRQMpZmY2Tug+Og+17W73A+ldCmxNeYmHXKP++pEvhaeOaI8qBbmq8PBvbv3YZS4Uj3TGwOjZPJemFFVYoOHrcRjiybTlLrJDXeUHEfKgNuNs5Z/R8FvP03VDkVHlwJwxNRfUcIc0yUS0HTAE9dAt51FWRW1e64epzxy5XaChAOBplerjV7Nd3R8sdeAN8NOsOIbBxJBY30sFLb2mzDFsLl61Ah35HfgDLN5+mM4CUG6QhZTwFFDF+oyDvqSslwx+3FOLQ43XB98fDyRjzzgFWyIsktNmDpNu96wsyguD1fetfZAFRnqci5TCNHXWv4OGAOCRX4TnJVMBoPY4HACIQ06ww+V5B2UpWD0fMmW7P8lIP+WBpYDoyf2VrOZ9LLBzHOKo8zkCZ7JIbMWS9wew4IYtjNTxZ4jBAfdAwJlKgb0OPLpUPT7h5P71dQncrvarQTRMSvbqnJN6hwOtHtRsBYHhPPs2SVqIY9CUdbgV4xI78l9Cy/4os2o7opO9sf5S0vHp3PvgFNW+66QOxBSBANKNVSgGwBr8KKcDDPPZ9umh9jDfaKpuca/g8QMVTIwQ602tOOkH1mwjP0llBaqtF1rij1DmgrcQL6imufWtAQgv/XMaLZfVBnjii0s9lraBdJKtaB4/Sn6uefX354Y=
